import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header style={{ padding: "10px", borderBottom: "1px solid #ccc" }}>
          <nav>
            <Link href="/" style={{ margin: "0 10px" }}>
              ホーム
            </Link>
            <Link href="/articles" style={{ margin: "0 10px" }}>
              記事一覧
            </Link>
            <Link href="/tags" style={{ margin: "0 10px" }}>
              タグ一覧
            </Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
