import { marked } from "marked";
import prisma from "../../lib/db";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "yuyujan.dev",
  description: "Generated by create next app",
};
export default async function Home() {
  const latestArticle = await prisma.article.findFirstOrThrow({
    orderBy: {
      updated_time: "desc",
    },
  });
  const html = marked.parse(latestArticle.article_text);
  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
export const dynamic = "force-dynamic";
