import React from "react";
import prisma from "../../../lib/db";
import Link from "next/link";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "記事一覧 - yuyujan.dev",
  description: "Generated by create next app",
};
export const dynamic = "force-dynamic";
export default async function getArticles() {
  const articles = await prisma.article.findMany();

  const listItems = articles.map((a, index) => (
    <div key={index} style={{ border: "1px solid #fff", padding: "10px", margin: "5px" }}>
      <Link href={`/article/${a.en_title}`}>
        {a.jp_title} - {a.en_title}
      </Link>
    </div>
  ));
  return listItems;
}
